qualfacul/hades

- profissa/src/main/java/com/profissa/home/HomeController.java
:information_source: [Setup inicial de um Spring RestController](https://spring.io/guides/gs/rest-service/)
> [15] - Adiciona HomeController

- build.gradle
- src/main/java/br/com/aprendi/AprendiApplication.java
- src/main/java/br/com/aprendi/configuration/JPAConfig.java
- src/main/java/br/com/aprendi/configuration/ServletContainerConfig.java
- src/main/java/br/com/aprendi/configuration/WebConfig.java
- src/main/java/br/com/aprendi/home/HomeController.java
- src/main/java/br/com/aprendi/home/TesteRepo.java
- src/main/java/br/com/aprendi/repository/Teste.java
- src/main/java/br/com/aprendi/repository/TesteRepo.java
- src/main/resources/application.properties.sample
- src/main/resources/log4j.properties
Adiciona Configurações para JPA e log4j
> [add-jpa-config] - Adiciona configuracoes para JPA e log4j

- src/main/java/com/hades/configuration/security/TokenAuthenticationService.java
- src/main/java/com/hades/configuration/security/TokenHandler.java
- src/main/java/com/hades/home/HomeController.java
- src/main/java/com/hades/login/LoggedUser.java
- src/main/java/com/hades/login/LoggedUserManager.java
- src/main/java/com/hades/user/auth/UserDAO.java
Adiciona classe ``LoggedUser``, responsavel por gerenciar o usuario da sessão.
> [36] - Adiciona LoggedUser

- .gitignore
- build.gradle
- src/main/java/com/hades/configuration/ServletContainerConfiguration.java
- src/main/resources/application.properties.sample
:warning: Todas as rotas agora são protegidas, usar ``https://localhost:6660``
> [38] - Altera servletContainer para undertow e adiciona http2

- build.gradle
- src/main/java/com/hades/login/LoginController.java
- src/main/java/com/hades/login/LoginInfo.java
- src/main/java/com/hades/login/LoginInfoDAO.java
> [33] - Criptografar senha do usuário ao salvar no banco de dados

- build.gradle
- src/main/java/com/hades/configuration/security/TokenAuthenticationService.java
- src/test/java/com/hades/configuration/security/TokenAuthenticationServiceTest.java
@ericdallo
Rodar ``gradle test`` para rodar todos os tests encontrados no diretorio ``/src/test``.
> [45] - Adiciona testes de unidade

- src/main/java/com/hades/annotation/Delete.java
- src/main/java/com/hades/annotation/Get.java
- src/main/java/com/hades/annotation/Patch.java
- src/main/java/com/hades/annotation/Post.java
- src/main/java/com/hades/annotation/Put.java
- src/main/java/com/hades/configuration/WebConfiguration.java
- src/main/java/com/hades/home/HomeController.java
- src/main/java/com/hades/login/LoginController.java
- src/main/java/com/hades/user/UserController.java
@ericdallo
- ``@POST``
- ``@GET``
- ``@PUT``
- ``@DELETE``
> [47] - Adiciona Endpoints personalizados

- src/main/java/com/hades/admin/Admin.java
- src/main/java/com/hades/admin/AdminController.java
- src/main/java/com/hades/admin/AdminDAO.java
- src/main/java/com/hades/admin/AdminDTO.java
- src/main/java/com/hades/admin/AdminRepository.java
- src/main/java/com/hades/login/LoginInfo.java
- src/main/java/com/hades/login/LoginInfoDAO.java
- src/main/java/com/hades/login/LoginOrigin.java
- src/main/java/com/hades/user/User.java
- src/main/java/com/hades/user/UserController.java
- src/main/java/com/hades/user/UserDAO.java
- src/main/java/com/hades/user/UserDTO.java
- src/main/java/com/hades/user/UserRepository.java
@brunogeronimo
- Verificar se as telas de cadastro não apresentam problemas após a alteração.
> [40] - Adiciona cadastro de administrador

- src/main/java/com/hades/admin/AdminController.java
- src/main/java/com/hades/annotation/Delete.java
- src/main/java/com/hades/annotation/Get.java
- src/main/java/com/hades/annotation/Patch.java
- src/main/java/com/hades/annotation/Post.java
- src/main/java/com/hades/annotation/Put.java
- src/main/java/com/hades/user/UserController.java
- src/main/java/com/hades/user/UserDTO.java
@ericdallo
Exemplo: 
```java
@Post(value = "/register", responseStatus = CREATED)
```
> [hackweekend-status-endpoints] - Adiciona status do response nas annotations de endpoints

- configuration/nginx.conf
- startup.sh
> [48] - Adicona configuracao do nginx

- build.gradle
- src/main/java/com/hades/annotation/InternalEndpoint.java
- src/main/java/com/hades/college/College.java
- src/main/java/com/hades/college/CollegeController.java
- src/main/java/com/hades/college/CollegeGrade.java
- src/main/java/com/hades/college/CollegeRepository.java
- src/main/java/com/hades/college/converter/CollegeMecDTOToCollegeConverter.java
- src/main/java/com/hades/interceptor/StatelessAuthenticationInterceptor.java
- src/main/resources/application.properties.sample
- src/test/java/com/hades/college/CollegeControllerTest.java
- src/test/java/com/hades/college/converter/CollegeMecDTOToCollegeConverterTest.java
@ericdallo
:warning: Depende do https://github.com/qualfacul/poseidon/pull/1 :warning: 
Adiciona endpoint ``/admin/{version}/colleges`` para salvar uma college do ``poseidon``
> [62] - Adiciona Task para popular faculdades do Brasil (Controller)

- src/main/java/com/hades/admin/AdminController.java
- src/main/java/com/hades/login/LoginController.java
- src/main/java/com/hades/login/LoginInfo.java
- src/main/java/com/hades/login/LoginInfoDTO.java
- src/main/java/com/hades/login/LoginService.java
- src/main/java/com/hades/login/LoginServiceCallback.java
- src/main/java/com/hades/login/LogingServiceCallback.java
- src/main/java/com/hades/social/SocialService.java
- src/main/java/com/hades/user/UserController.java
- src/test/java/com/hades/login/LoginServiceTest.java
> [fix-login] - Corrige login

- src/main/java/com/qualfacul/hades/exceptions/EmailAlreadyInUseException.java
- src/main/java/com/qualfacul/hades/login/LoginInfo.java
- src/main/java/com/qualfacul/hades/user/UserController.java
- Corrige erro ao realizar cadastro com um e-mail já existente no sistema;
1. No zeus, acesse a tela de cadastro;
2. Faça um cadastro com um e-mail a sua escolha;
3. Faça logoff e tente criar uma nova conta utilizando o mesmo e-mail do passo 2;
4. A mensagem `This e-mail address is already in use` deverá ser retornada.
> [46] - Tratamento de e-mail sendo utilizado

- src/main/java/com/qualfacul/hades/college/CollegeController.java
- src/main/java/com/qualfacul/hades/search/PaginatedSearch.java
- src/main/java/com/qualfacul/hades/search/SearchQuery.java
- src/main/java/com/qualfacul/hades/social/FacebookLogin.java
- src/main/java/com/qualfacul/hades/social/FacebookLoginController.java
- src/main/java/com/qualfacul/hades/social/FacebookLoginDTO.java
depende de: https://github.com/qualfacul/zeus/pull/27
Adiciona modelo de FacebookLogin para receber no endpoint `/facebook/login`
> [95] - Fix endpoint de login do facebook e Busca de faculdades

- src/main/java/com/qualfacul/hades/HadesTasksApplication.java
- src/main/java/com/qualfacul/hades/annotation/WebConfiguration.java
- src/main/java/com/qualfacul/hades/college/College.java
- src/main/java/com/qualfacul/hades/college/CollegeAddress.java
- src/main/java/com/qualfacul/hades/college/CollegeController.java
- src/main/java/com/qualfacul/hades/college/CollegeGrade.java
- src/main/java/com/qualfacul/hades/college/CollegeToCollegeDTOConverter.java
- src/main/java/com/qualfacul/hades/configuration/SearchIndexInitializer.java
- src/main/java/com/qualfacul/hades/configuration/WebConfig.java
- src/main/java/com/qualfacul/hades/course/Course.java
- src/main/java/com/qualfacul/hades/course/CourseDTO.java
- src/main/java/com/qualfacul/hades/course/CourseGrade.java
- src/main/java/com/qualfacul/hades/course/CourseGradeDTO.java
- src/main/java/com/qualfacul/hades/course/CourseToDTOConverter.java
- src/main/java/com/qualfacul/hades/mec/MecCollegeService.java
- src/main/java/com/qualfacul/hades/mec/MecCourseService.java
- src/main/java/com/qualfacul/hades/mec/MecRequester.java
- src/main/java/com/qualfacul/hades/task/MECInformationsTasks.java
- src/test/java/com/qualfacul/hades/college/CollegeToCollegeDTOConverterTest.java
:warning: Depende do  https://github.com/qualfacul/hades/pull/35  :warning: 
💣  faz o rebase
``GET`` ``/colleges/{collegeId}/courses``
> [add-courses-endpoint] - Adiciona endpoint para listar todos os cursos de uma faculdade

- src/main/java/com/qualfacul/hades/college/College.java
- src/main/java/com/qualfacul/hades/college/CollegeController.java
- src/main/java/com/qualfacul/hades/college/CollegeDTO.java
- src/main/java/com/qualfacul/hades/college/CollegeGrade.java
- src/main/java/com/qualfacul/hades/college/CollegeGradeDTO.java
- src/main/java/com/qualfacul/hades/college/CollegeGradeOrigin.java
- src/main/java/com/qualfacul/hades/college/CollegeGradeToDTOConverter.java
- src/main/java/com/qualfacul/hades/college/CollegeToCollegeDTOConverter.java
- src/main/java/com/qualfacul/hades/college/SimpleCollegeGradeDTO.java
- src/main/java/com/qualfacul/hades/login/LoggedUserManager.java
- src/test/java/com/qualfacul/hades/college/CollegeToCollegeDTOConverterTest.java
> [I53] - Adiciona endpoint para retorno de avaliacoes e para avaliar

- src/main/java/com/qualfacul/hades/admin/Admin.java
- src/main/java/com/qualfacul/hades/college/College.java
- src/main/java/com/qualfacul/hades/college/CollegeAddress.java
- src/main/java/com/qualfacul/hades/college/rank/CollegeRank.java
- src/main/java/com/qualfacul/hades/conversation/Conversation.java
- src/main/java/com/qualfacul/hades/conversation/Message.java
- src/main/java/com/qualfacul/hades/course/Course.java
- src/main/java/com/qualfacul/hades/login/LoginInfo.java
- src/main/java/com/qualfacul/hades/user/User.java
- src/main/java/com/qualfacul/hades/user/address/UserCollegeAddress.java
As seguintes tabelas foram revisadas:
- `admin`
- `college`
- `college_address`
- `college_rank`
- `conversation`
- `message`
- `course`
- `login_info`
- `user`
- `user_college_address`
> [I48] - Revisão das tabelas do banco de dados

- src/main/java/com/qualfacul/hades/course/Course.java
- src/main/java/com/qualfacul/hades/course/CourseController.java
- src/main/java/com/qualfacul/hades/course/CourseDTO.java
- src/main/java/com/qualfacul/hades/course/CourseToDTOConverter.java
- src/main/java/com/qualfacul/hades/search/PaginatedResult.java
> [I60] - Adiciona endpoint para pesquisa de cursos

- src/main/java/com/qualfacul/hades/college/CollegeController.java
- src/main/java/com/qualfacul/hades/college/rank/CollegeRankDTO.java
- src/main/java/com/qualfacul/hades/college/rank/CollegeRankNotFoundException.java
endpoint - `/colleges/{collegeId}/ranking?type={CollegeRankType}`
> [I69] - Adiciona endpoint para retornar um ranking de uma faculdade

- src/main/java/com/qualfacul/hades/college/CollegeController.java
- src/main/java/com/qualfacul/hades/college/CollegeDTO.java
- src/main/java/com/qualfacul/hades/college/CollegeToCollegeDTOConverter.java
- src/main/java/com/qualfacul/hades/mec/MecCollegeService.java
- src/main/java/com/qualfacul/hades/search/CollegeSearchFilter.java
- src/main/java/com/qualfacul/hades/search/SearchFilter.java
- src/main/java/com/qualfacul/hades/search/SearchQuery.java
⚠️  depende de https://github.com/qualfacul/zeus/pull/98
> [I51] - Adiciona filtros na pesquisa de faculdades

- src/main/java/com/qualfacul/hades/exceptions/AccessDeniedException.java
- src/main/java/com/qualfacul/hades/user/UserController.java
- src/main/java/com/qualfacul/hades/user/UserRepository.java
- src/main/java/com/qualfacul/hades/user/UserSettingsDTO.java
Endpoint `/users/preferences` criado. Nele o usuário poderá alterar seu nome e sua senha.
> [I46] Endpoint para alteração do usuário concluido
